/* The following code was generated by JFlex 1.7.0 */

//lexer.flex
//用户代码段
import java_cup.runtime.*;
import java.io.*;
import exceptions.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>lexer.flex</tt>
 */
class lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\11\1\14\1\13\1\70\1\14\1\12\16\11\4\0\1\14\2\0"+
    "\1\24\1\10\1\0\1\35\1\0\1\5\1\7\1\6\1\25\1\17"+
    "\1\26\1\16\1\0\1\2\7\3\2\1\1\20\1\15\1\21\1\22"+
    "\1\23\2\0\1\52\1\51\1\53\1\27\1\41\1\44\1\50\1\46"+
    "\1\30\2\10\1\42\1\32\1\47\1\33\1\56\1\10\1\34\1\43"+
    "\1\45\1\57\1\31\1\55\1\10\1\54\1\10\1\37\1\0\1\40"+
    "\1\0\1\10\1\0\1\64\2\10\1\65\1\63\3\10\1\61\2\10"+
    "\1\66\1\10\1\67\3\10\1\60\1\10\1\62\6\10\1\0\1\4"+
    "\1\0\1\36\6\11\1\71\32\11\2\0\4\10\4\0\1\10\2\0"+
    "\1\11\7\0\1\10\4\0\1\10\5\0\27\10\1\0\37\10\1\0"+
    "\u01ca\10\4\0\14\10\16\0\5\10\7\0\1\10\1\0\1\10\21\0"+
    "\160\11\5\10\1\0\2\10\2\0\4\10\1\0\1\10\6\0\1\10"+
    "\1\0\3\10\1\0\1\10\1\0\24\10\1\0\123\10\1\0\213\10"+
    "\1\0\5\11\2\0\246\10\1\0\46\10\2\0\1\10\7\0\47\10"+
    "\7\0\1\10\1\0\55\11\1\0\1\11\1\0\2\11\1\0\2\11"+
    "\1\0\1\11\10\0\33\10\5\0\3\10\15\0\6\11\5\0\1\10"+
    "\4\0\13\11\1\0\1\11\3\0\53\10\37\11\4\0\2\10\1\11"+
    "\143\10\1\0\1\10\10\11\1\0\6\11\2\10\2\11\1\0\4\11"+
    "\2\10\12\11\3\10\2\0\1\10\17\0\1\11\1\10\1\11\36\10"+
    "\33\11\2\0\131\10\13\11\1\10\16\0\12\11\41\10\11\11\2\10"+
    "\4\0\1\10\5\0\26\10\4\11\1\10\11\11\1\10\3\11\1\10"+
    "\5\11\22\0\31\10\3\11\4\0\13\10\65\0\25\10\1\0\10\10"+
    "\26\0\60\11\66\10\3\11\1\10\22\11\1\10\7\11\12\10\2\11"+
    "\2\0\12\11\1\0\20\10\3\11\1\0\10\10\2\0\2\10\2\0"+
    "\26\10\1\0\7\10\1\0\1\10\3\0\4\10\2\0\1\11\1\10"+
    "\7\11\2\0\2\11\2\0\3\11\1\10\10\0\1\11\4\0\2\10"+
    "\1\0\3\10\2\11\2\0\12\11\4\10\7\0\2\10\4\0\3\11"+
    "\1\0\6\10\4\0\2\10\2\0\26\10\1\0\7\10\1\0\2\10"+
    "\1\0\2\10\1\0\2\10\2\0\1\11\1\0\5\11\4\0\2\11"+
    "\2\0\3\11\3\0\1\11\7\0\4\10\1\0\1\10\7\0\14\11"+
    "\3\10\1\11\13\0\3\11\1\0\11\10\1\0\3\10\1\0\26\10"+
    "\1\0\7\10\1\0\2\10\1\0\5\10\2\0\1\11\1\10\10\11"+
    "\1\0\3\11\1\0\3\11\2\0\1\10\17\0\2\10\2\11\2\0"+
    "\12\11\1\0\1\10\7\0\1\10\6\11\1\0\3\11\1\0\10\10"+
    "\2\0\2\10\2\0\26\10\1\0\7\10\1\0\2\10\1\0\5\10"+
    "\2\0\1\11\1\10\7\11\2\0\2\11\2\0\3\11\10\0\2\11"+
    "\4\0\2\10\1\0\3\10\2\11\2\0\12\11\1\0\1\10\20\0"+
    "\1\11\1\10\1\0\6\10\3\0\3\10\1\0\4\10\3\0\2\10"+
    "\1\0\1\10\1\0\2\10\3\0\2\10\3\0\3\10\3\0\14\10"+
    "\4\0\5\11\3\0\3\11\1\0\4\11\2\0\1\10\6\0\1\11"+
    "\16\0\12\11\11\0\1\10\6\0\4\11\1\0\10\10\1\0\3\10"+
    "\1\0\27\10\1\0\20\10\3\0\1\10\7\11\1\0\3\11\1\0"+
    "\4\11\7\0\2\11\1\0\3\10\5\0\2\10\2\11\2\0\12\11"+
    "\20\0\1\10\3\11\1\0\10\10\1\0\3\10\1\0\27\10\1\0"+
    "\12\10\1\0\5\10\2\0\1\11\1\10\7\11\1\0\3\11\1\0"+
    "\4\11\7\0\2\11\7\0\1\10\1\0\2\10\2\11\2\0\12\11"+
    "\1\0\2\10\15\0\4\11\1\0\10\10\1\0\3\10\1\0\51\10"+
    "\2\11\1\10\7\11\1\0\3\11\1\0\4\11\1\10\5\0\3\10"+
    "\1\11\7\0\3\10\2\11\2\0\12\11\12\0\6\10\2\0\2\11"+
    "\1\0\22\10\3\0\30\10\1\0\11\10\1\0\1\10\2\0\7\10"+
    "\3\0\1\11\4\0\6\11\1\0\1\11\1\0\10\11\6\0\12\11"+
    "\2\0\2\11\15\0\60\10\1\11\2\10\7\11\4\0\10\10\10\11"+
    "\1\0\12\11\47\0\2\10\1\0\1\10\2\0\2\10\1\0\1\10"+
    "\2\0\1\10\6\0\4\10\1\0\7\10\1\0\3\10\1\0\1\10"+
    "\1\0\1\10\2\0\2\10\1\0\4\10\1\11\2\10\6\11\1\0"+
    "\2\11\1\10\2\0\5\10\1\0\1\10\1\0\6\11\2\0\12\11"+
    "\2\0\4\10\40\0\1\10\27\0\2\11\6\0\12\11\13\0\1\11"+
    "\1\0\1\11\1\0\1\11\4\0\2\11\10\10\1\0\44\10\4\0"+
    "\24\11\1\0\2\11\5\10\13\11\1\0\44\11\11\0\1\11\71\0"+
    "\53\10\24\11\1\10\12\11\6\0\6\10\4\11\4\10\3\11\1\10"+
    "\3\11\2\10\7\11\3\10\4\11\15\10\14\11\1\10\17\11\2\0"+
    "\46\10\1\0\1\10\5\0\1\10\2\0\53\10\1\0\u014d\10\1\0"+
    "\4\10\2\0\7\10\1\0\1\10\1\0\4\10\2\0\51\10\1\0"+
    "\4\10\2\0\41\10\1\0\4\10\2\0\7\10\1\0\1\10\1\0"+
    "\4\10\2\0\17\10\1\0\71\10\1\0\4\10\2\0\103\10\2\0"+
    "\3\11\40\0\20\10\20\0\126\10\2\0\6\10\3\0\u026c\10\2\0"+
    "\21\10\1\0\32\10\5\0\113\10\3\0\13\10\7\0\15\10\1\0"+
    "\4\10\3\11\13\0\22\10\3\11\13\0\22\10\2\11\14\0\15\10"+
    "\1\0\3\10\1\0\2\11\14\0\64\10\40\11\3\0\1\10\3\0"+
    "\2\10\1\11\2\0\12\11\41\0\4\11\1\0\12\11\6\0\130\10"+
    "\10\0\5\10\2\11\42\10\1\11\1\10\5\0\106\10\12\0\37\10"+
    "\1\0\14\11\4\0\14\11\12\0\12\11\36\10\2\0\5\10\13\0"+
    "\54\10\4\0\32\10\6\0\12\11\46\0\27\10\5\11\4\0\65\10"+
    "\12\11\1\0\35\11\2\0\13\11\6\0\12\11\15\0\1\10\10\0"+
    "\16\11\102\0\5\11\57\10\21\11\7\10\4\0\12\11\21\0\11\11"+
    "\14\0\3\11\36\10\15\11\2\10\12\11\54\10\16\11\14\0\44\10"+
    "\24\11\10\0\12\11\3\0\3\10\12\11\44\10\2\0\11\10\107\0"+
    "\3\11\1\0\25\11\4\10\1\11\4\10\3\11\2\10\3\11\6\0"+
    "\300\10\72\11\1\0\5\11\u0116\10\2\0\6\10\2\0\46\10\2\0"+
    "\6\10\2\0\10\10\1\0\1\10\1\0\1\10\1\0\1\10\1\0"+
    "\37\10\2\0\65\10\1\0\7\10\1\0\1\10\3\0\3\10\1\0"+
    "\7\10\3\0\4\10\2\0\6\10\4\0\15\10\5\0\3\10\1\0"+
    "\7\10\16\0\5\11\30\0\1\70\1\70\5\11\20\0\2\10\23\0"+
    "\1\10\13\0\5\11\1\0\12\11\1\0\1\10\15\0\1\10\20\0"+
    "\15\10\3\0\40\10\20\0\15\11\4\0\1\11\3\0\14\11\21\0"+
    "\1\10\4\0\1\10\2\0\12\10\1\0\1\10\3\0\5\10\6\0"+
    "\1\10\1\0\1\10\1\0\1\10\1\0\4\10\1\0\13\10\2\0"+
    "\4\10\5\0\5\10\4\0\1\10\21\0\51\10\u0a77\0\57\10\1\0"+
    "\57\10\1\0\205\10\6\0\4\10\3\11\2\10\14\0\46\10\1\0"+
    "\1\10\5\0\1\10\2\0\70\10\7\0\1\10\17\0\1\11\27\10"+
    "\11\0\7\10\1\0\7\10\1\0\7\10\1\0\7\10\1\0\7\10"+
    "\1\0\7\10\1\0\7\10\1\0\7\10\1\0\40\11\57\0\1\10"+
    "\u01d5\0\3\10\31\0\11\10\6\11\1\0\5\10\2\0\5\10\4\0"+
    "\126\10\2\0\2\11\2\0\3\10\1\0\132\10\1\0\4\10\5\0"+
    "\52\10\2\0\136\10\21\0\33\10\65\0\20\10\u0200\0\u19b6\10\112\0"+
    "\u51eb\10\25\0\u048d\10\103\0\56\10\2\0\u010d\10\3\0\20\10\12\11"+
    "\2\10\24\0\57\10\1\11\4\0\12\11\1\0\37\10\2\11\120\10"+
    "\2\11\45\0\11\10\2\0\147\10\2\0\44\10\1\0\10\10\77\0"+
    "\13\10\1\11\3\10\1\11\4\10\1\11\27\10\5\11\20\0\1\10"+
    "\7\0\64\10\14\0\2\11\62\10\22\11\12\0\12\11\6\0\22\11"+
    "\6\10\3\0\1\10\1\0\1\10\2\0\12\11\34\10\10\11\2\0"+
    "\27\10\15\11\14\0\35\10\3\0\4\11\57\10\16\11\16\0\1\10"+
    "\12\11\6\0\5\10\1\11\12\10\12\11\5\10\1\0\51\10\16\11"+
    "\11\0\3\10\1\11\10\10\2\11\2\0\12\11\6\0\27\10\3\0"+
    "\1\10\3\11\62\10\1\11\1\10\3\11\2\10\2\11\5\10\2\11"+
    "\1\10\1\11\1\10\30\0\3\10\2\0\13\10\5\11\2\0\3\10"+
    "\2\11\12\0\6\10\2\0\6\10\2\0\6\10\11\0\7\10\1\0"+
    "\7\10\1\0\53\10\1\0\12\10\12\0\163\10\10\11\1\0\2\11"+
    "\2\0\12\11\6\0\u2ba4\10\14\0\27\10\4\0\61\10\u2104\0\u016e\10"+
    "\2\0\152\10\46\0\7\10\14\0\5\10\5\0\1\10\1\11\12\10"+
    "\1\0\15\10\1\0\5\10\1\0\1\10\1\0\2\10\1\0\2\10"+
    "\1\0\154\10\41\0\u016b\10\22\0\100\10\2\0\66\10\50\0\15\10"+
    "\3\0\20\11\20\0\20\11\3\0\2\10\30\0\3\10\31\0\1\10"+
    "\6\0\5\10\1\0\207\10\2\0\1\11\4\0\1\10\13\0\12\11"+
    "\7\0\32\10\4\0\1\10\1\0\32\10\13\0\131\10\3\0\6\10"+
    "\2\0\6\10\2\0\6\10\2\0\3\10\3\0\2\10\3\0\2\10"+
    "\22\0\3\11\4\0\14\10\1\0\32\10\1\0\23\10\1\0\2\10"+
    "\1\0\17\10\2\0\16\10\42\0\173\10\105\0\65\10\210\0\1\11"+
    "\202\0\35\10\3\0\61\10\17\0\1\11\37\0\40\10\15\0\36\10"+
    "\5\0\46\10\5\11\5\0\36\10\2\0\44\10\4\0\10\10\1\0"+
    "\5\10\52\0\236\10\2\0\12\11\6\0\44\10\4\0\44\10\4\0"+
    "\50\10\10\0\64\10\234\0\u0137\10\11\0\26\10\12\0\10\10\230\0"+
    "\6\10\2\0\1\10\1\0\54\10\1\0\2\10\3\0\1\10\2\0"+
    "\27\10\12\0\27\10\11\0\37\10\101\0\23\10\1\0\2\10\12\0"+
    "\26\10\12\0\32\10\106\0\70\10\6\0\2\10\100\0\1\10\3\11"+
    "\1\0\2\11\5\0\4\11\4\10\1\0\3\10\1\0\33\10\4\0"+
    "\3\11\4\0\1\11\40\0\35\10\3\0\35\10\43\0\10\10\1\0"+
    "\34\10\2\11\31\0\66\10\12\0\26\10\12\0\23\10\15\0\22\10"+
    "\156\0\111\10\67\0\63\10\15\0\63\10\u030d\0\3\11\65\10\17\11"+
    "\37\0\12\11\17\0\4\11\55\10\13\11\2\0\1\11\22\0\31\10"+
    "\7\0\12\11\6\0\3\11\44\10\16\11\1\0\12\11\20\0\43\10"+
    "\1\11\2\0\1\10\11\0\3\11\60\10\16\11\4\10\5\0\3\11"+
    "\3\0\12\11\1\10\1\0\1\10\43\0\22\10\1\0\31\10\14\11"+
    "\6\0\1\11\101\0\7\10\1\0\1\10\1\0\4\10\1\0\17\10"+
    "\1\0\12\10\7\0\57\10\14\11\5\0\12\11\6\0\4\11\1\0"+
    "\10\10\2\0\2\10\2\0\26\10\1\0\7\10\1\0\2\10\1\0"+
    "\5\10\2\0\1\11\1\10\7\11\2\0\2\11\2\0\3\11\2\0"+
    "\1\10\6\0\1\11\5\0\5\10\2\11\2\0\7\11\3\0\5\11"+
    "\213\0\65\10\22\11\4\10\5\0\12\11\46\0\60\10\24\11\2\10"+
    "\1\0\1\10\10\0\12\11\246\0\57\10\7\11\2\0\11\11\27\0"+
    "\4\10\2\11\42\0\60\10\21\11\3\0\1\10\13\0\12\11\46\0"+
    "\53\10\15\11\10\0\12\11\66\0\32\10\3\0\17\11\4\0\12\11"+
    "\u0166\0\100\10\12\11\25\0\1\10\u0100\0\1\10\12\11\50\10\7\11"+
    "\1\10\4\11\10\0\1\11\10\0\1\10\13\11\50\10\2\0\4\10"+
    "\20\11\46\0\71\10\u0107\0\11\10\1\0\45\10\10\11\1\0\10\11"+
    "\1\10\17\0\12\11\30\0\36\10\2\0\26\11\1\0\16\11\111\0"+
    "\7\10\1\0\2\10\1\0\46\10\6\11\3\0\1\11\1\0\2\11"+
    "\1\0\7\11\1\10\1\11\10\0\12\11\u02a6\0\u039a\10\146\0\157\10"+
    "\21\0\304\10\u0abc\0\u042f\10\u0fd1\0\u0247\10\u21b9\0\u0239\10\7\0\37\10"+
    "\1\0\12\11\146\0\36\10\2\0\5\11\13\0\60\10\7\11\11\0"+
    "\4\10\14\0\12\11\11\0\25\10\5\0\23\10\u0370\0\105\10\13\0"+
    "\1\10\56\11\20\0\4\11\15\10\100\0\2\10\36\0\u17ed\10\23\0"+
    "\u02f3\10\u250d\0\u011f\10\121\0\u018c\10\u0904\0\153\10\5\0\15\10\3\0"+
    "\11\10\7\0\12\10\3\0\2\11\1\0\4\11\u14c1\0\5\11\3\0"+
    "\26\11\2\0\7\11\36\0\4\11\224\0\3\11\u01bb\0\125\10\1\0"+
    "\107\10\1\0\2\10\2\0\1\10\2\0\2\10\2\0\4\10\1\0"+
    "\14\10\1\0\1\10\1\0\7\10\1\0\101\10\1\0\4\10\2\0"+
    "\10\10\1\0\7\10\1\0\34\10\1\0\4\10\1\0\5\10\1\0"+
    "\1\10\3\0\7\10\1\0\u0154\10\2\0\31\10\1\0\31\10\1\0"+
    "\37\10\1\0\31\10\1\0\37\10\1\0\31\10\1\0\37\10\1\0"+
    "\31\10\1\0\37\10\1\0\31\10\1\0\10\10\2\0\62\11\u0200\0"+
    "\67\11\4\0\62\11\10\0\1\11\16\0\1\11\26\0\5\11\1\0"+
    "\17\11\u0550\0\7\11\1\0\21\11\2\0\7\11\1\0\2\11\1\0"+
    "\5\11\u07d5\0\305\10\13\0\7\11\51\0\104\10\7\11\5\0\12\11"+
    "\u04a6\0\4\10\1\0\33\10\1\0\2\10\1\0\1\10\2\0\1\10"+
    "\1\0\12\10\1\0\4\10\1\0\1\10\1\0\1\10\6\0\1\10"+
    "\4\0\1\10\1\0\1\10\1\0\1\10\1\0\3\10\1\0\2\10"+
    "\1\0\1\10\2\0\1\10\1\0\1\10\1\0\1\10\1\0\1\10"+
    "\1\0\1\10\1\0\2\10\1\0\1\10\2\0\4\10\1\0\7\10"+
    "\1\0\4\10\1\0\4\10\1\0\1\10\1\0\12\10\1\0\21\10"+
    "\5\0\3\10\1\0\5\10\1\0\21\10\u1144\0\ua6d7\10\51\0\u1035\10"+
    "\13\0\336\10\2\0\u1682\10\16\0\u1d31\10\u0c1f\0\u021e\10\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\u05ee\0"+
    "\1\11\36\0\140\11\200\0\360\11\uffff\0\uffff\0\ufe12\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\1\4\1\5\1\6\2\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\6\6\1\22\1\23\1\24\1\25\7\6"+
    "\3\0\1\26\2\27\1\0\2\30\1\31\1\32\1\33"+
    "\1\6\1\34\1\35\3\6\1\36\1\37\15\6\2\27"+
    "\1\0\1\40\1\6\1\41\1\42\3\6\1\43\11\6"+
    "\1\30\1\44\3\6\1\45\1\6\1\46\1\47\1\50"+
    "\7\6\1\44\3\6\1\51\1\6\1\52\1\53\1\54"+
    "\1\55\1\56\1\6\1\30\1\0\1\6\1\57\1\60"+
    "\3\6\1\30\1\61\1\62\1\63\2\6\1\64";

  private static int [] zzUnpackAction() {
    int [] result = new int[134];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\72\0\164\0\256\0\350\0\u0122\0\72\0\u015c"+
    "\0\u0196\0\72\0\72\0\72\0\72\0\u01d0\0\u020a\0\72"+
    "\0\u0244\0\72\0\72\0\72\0\u027e\0\u02b8\0\u02f2\0\u032c"+
    "\0\u0366\0\u03a0\0\72\0\72\0\72\0\72\0\u03da\0\u0414"+
    "\0\u044e\0\u0488\0\u04c2\0\u04fc\0\u0536\0\72\0\u0570\0\u0122"+
    "\0\u05aa\0\u05e4\0\u061e\0\u0658\0\u0692\0\72\0\72\0\72"+
    "\0\72\0\u06cc\0\u015c\0\u015c\0\u0706\0\u0740\0\u077a\0\u015c"+
    "\0\u015c\0\u07b4\0\u07ee\0\u0828\0\u0862\0\u089c\0\u08d6\0\u0910"+
    "\0\u094a\0\u0984\0\u09be\0\u09f8\0\u0a32\0\u0a6c\0\u0aa6\0\u0ae0"+
    "\0\u0b1a\0\u015c\0\u0b54\0\u015c\0\u0b8e\0\u0bc8\0\u0c02\0\u0c3c"+
    "\0\u015c\0\u0c76\0\u0cb0\0\u0cea\0\u0d24\0\u0d5e\0\u0d98\0\u0dd2"+
    "\0\u0e0c\0\u0e46\0\u0e80\0\u0eba\0\u0ef4\0\u0f2e\0\u0f68\0\u015c"+
    "\0\u0fa2\0\u015c\0\u015c\0\u015c\0\u0fdc\0\u1016\0\u1050\0\u108a"+
    "\0\u10c4\0\u10fe\0\u1138\0\u1172\0\u11ac\0\u11e6\0\u1220\0\u015c"+
    "\0\u125a\0\u015c\0\u015c\0\u015c\0\u015c\0\u1294\0\u12ce\0\u1172"+
    "\0\u1308\0\u1342\0\u015c\0\u015c\0\u137c\0\u13b6\0\u13f0\0\u142a"+
    "\0\u015c\0\u015c\0\u015c\0\u1464\0\u149e\0\u015c";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[134];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\3\1\2\1\5\1\6\1\7"+
    "\1\10\1\2\1\11\2\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\3\10\1\40\3\10\1\41\1\42\1\43\1\10"+
    "\1\44\1\45\11\10\7\46\1\47\1\50\64\46\3\3"+
    "\1\46\1\47\1\50\1\46\1\51\16\46\6\51\4\46"+
    "\27\51\3\46\1\52\2\4\1\53\1\47\1\50\1\46"+
    "\1\51\16\46\6\51\4\46\27\51\7\46\1\54\1\55"+
    "\70\46\1\47\1\50\1\56\63\46\3\10\1\46\1\47"+
    "\1\50\1\46\2\10\15\46\6\10\4\46\27\10\1\46"+
    "\1\10\5\46\1\47\1\50\4\46\1\12\63\46\1\47"+
    "\1\50\13\46\1\57\54\46\1\47\1\50\13\46\1\60"+
    "\54\46\1\47\1\50\13\46\1\61\50\46\3\10\1\46"+
    "\1\47\1\50\1\46\2\10\15\46\1\10\1\62\2\10"+
    "\1\63\1\10\4\46\27\10\1\46\1\10\1\46\3\10"+
    "\1\46\1\47\1\50\1\46\2\10\15\46\6\10\4\46"+
    "\3\10\1\64\2\10\1\65\20\10\1\46\1\10\1\46"+
    "\3\10\1\46\1\47\1\50\1\46\2\10\15\46\6\10"+
    "\4\46\11\10\1\66\15\10\1\46\1\10\1\46\3\10"+
    "\1\46\1\47\1\50\1\46\2\10\15\46\4\10\1\67"+
    "\1\10\4\46\27\10\1\46\1\10\1\46\3\10\1\46"+
    "\1\47\1\50\1\46\2\10\15\46\5\10\1\70\4\46"+
    "\3\10\1\71\23\10\1\46\1\10\1\46\3\10\1\46"+
    "\1\47\1\50\1\46\2\10\15\46\6\10\4\46\1\72"+
    "\21\10\1\73\4\10\1\46\1\10\1\46\3\10\1\46"+
    "\1\47\1\50\1\46\2\10\15\46\6\10\4\46\1\10"+
    "\1\74\4\10\1\75\20\10\1\46\1\10\1\46\3\10"+
    "\1\46\1\47\1\50\1\46\2\10\15\46\6\10\4\46"+
    "\5\10\1\76\5\10\1\77\13\10\1\46\1\10\1\46"+
    "\3\10\1\46\1\47\1\50\1\46\2\10\15\46\4\10"+
    "\1\100\1\10\4\46\1\101\26\10\1\46\1\10\1\46"+
    "\3\10\1\46\1\47\1\50\1\46\2\10\15\46\5\10"+
    "\1\102\4\46\27\10\1\46\1\10\1\46\3\10\1\46"+
    "\1\47\1\50\1\46\2\10\15\46\4\10\1\103\1\10"+
    "\4\46\27\10\1\46\1\10\1\46\3\10\1\46\1\47"+
    "\1\50\1\46\2\10\15\46\6\10\4\46\5\10\1\104"+
    "\11\10\1\105\7\10\1\46\1\10\1\46\3\10\1\46"+
    "\1\47\1\50\1\46\2\10\15\46\5\10\1\106\4\46"+
    "\27\10\1\46\1\10\5\46\1\54\1\0\64\46\3\51"+
    "\1\46\1\47\1\50\1\46\2\51\15\46\6\51\4\46"+
    "\27\51\1\46\1\51\1\46\1\52\2\107\1\53\1\47"+
    "\1\50\1\46\1\51\16\46\6\51\4\46\27\51\3\46"+
    "\1\53\2\110\1\53\1\47\1\50\70\46\1\54\1\50"+
    "\63\46\6\55\1\111\63\55\1\46\3\10\1\46\1\47"+
    "\1\50\1\46\2\10\15\46\2\10\1\112\3\10\4\46"+
    "\27\10\1\46\1\10\1\46\3\10\1\46\1\47\1\50"+
    "\1\46\2\10\15\46\6\10\4\46\4\10\1\113\22\10"+
    "\1\46\1\10\1\46\3\10\1\46\1\47\1\50\1\46"+
    "\2\10\15\46\5\10\1\114\4\46\27\10\1\46\1\10"+
    "\1\46\3\10\1\46\1\47\1\50\1\46\2\10\15\46"+
    "\1\115\5\10\4\46\27\10\1\46\1\10\1\46\3\10"+
    "\1\46\1\47\1\50\1\46\2\10\15\46\6\10\4\46"+
    "\12\10\1\116\14\10\1\46\1\10\1\46\3\10\1\46"+
    "\1\47\1\50\1\46\2\10\15\46\6\10\4\46\23\10"+
    "\1\117\3\10\1\46\1\10\1\46\3\10\1\46\1\47"+
    "\1\50\1\46\2\10\15\46\6\10\4\46\2\10\1\120"+
    "\24\10\1\46\1\10\1\46\3\10\1\46\1\47\1\50"+
    "\1\46\2\10\15\46\1\121\5\10\4\46\27\10\1\46"+
    "\1\10\1\46\3\10\1\46\1\47\1\50\1\46\2\10"+
    "\15\46\6\10\4\46\1\122\26\10\1\46\1\10\1\46"+
    "\3\10\1\46\1\47\1\50\1\46\2\10\15\46\6\10"+
    "\4\46\15\10\1\123\11\10\1\46\1\10\1\46\3\10"+
    "\1\46\1\47\1\50\1\46\2\10\15\46\4\10\1\124"+
    "\1\10\4\46\27\10\1\46\1\10\1\46\3\10\1\46"+
    "\1\47\1\50\1\46\2\10\15\46\6\10\4\46\7\10"+
    "\1\125\17\10\1\46\1\10\1\46\3\10\1\46\1\47"+
    "\1\50\1\46\2\10\15\46\5\10\1\126\4\46\27\10"+
    "\1\46\1\10\1\46\3\10\1\46\1\47\1\50\1\46"+
    "\2\10\15\46\6\10\4\46\6\10\1\127\20\10\1\46"+
    "\1\10\1\46\3\10\1\46\1\47\1\50\1\46\2\10"+
    "\15\46\1\10\1\130\4\10\4\46\27\10\1\46\1\10"+
    "\1\46\3\10\1\46\1\47\1\50\1\46\2\10\15\46"+
    "\6\10\4\46\20\10\1\131\6\10\1\46\1\10\1\46"+
    "\3\10\1\46\1\47\1\50\1\46\2\10\15\46\4\10"+
    "\1\132\1\10\4\46\27\10\1\46\1\10\1\46\3\107"+
    "\1\46\1\47\1\50\1\46\1\51\16\46\6\51\4\46"+
    "\27\51\3\46\3\110\1\46\1\47\1\50\63\46\6\55"+
    "\1\133\1\134\62\55\1\46\3\10\1\46\1\47\1\50"+
    "\1\46\2\10\15\46\6\10\4\46\1\135\26\10\1\46"+
    "\1\10\1\46\3\10\1\46\1\47\1\50\1\46\2\10"+
    "\15\46\6\10\4\46\16\10\1\136\10\10\1\46\1\10"+
    "\1\46\3\10\1\46\1\47\1\50\1\46\2\10\15\46"+
    "\4\10\1\137\1\10\4\46\27\10\1\46\1\10\1\46"+
    "\3\10\1\46\1\47\1\50\1\46\2\10\15\46\6\10"+
    "\4\46\24\10\1\140\2\10\1\46\1\10\1\46\3\10"+
    "\1\46\1\47\1\50\1\46\2\10\15\46\1\10\1\141"+
    "\4\10\4\46\1\142\26\10\1\46\1\10\1\46\3\10"+
    "\1\46\1\47\1\50\1\46\2\10\15\46\6\10\4\46"+
    "\6\10\1\143\20\10\1\46\1\10\1\46\3\10\1\46"+
    "\1\47\1\50\1\46\2\10\15\46\6\10\4\46\1\144"+
    "\26\10\1\46\1\10\1\46\3\10\1\46\1\47\1\50"+
    "\1\46\2\10\15\46\6\10\4\46\1\10\1\145\25\10"+
    "\1\46\1\10\1\46\3\10\1\46\1\47\1\50\1\46"+
    "\2\10\15\46\1\10\1\146\4\10\4\46\27\10\1\46"+
    "\1\10\1\46\3\10\1\46\1\47\1\50\1\46\2\10"+
    "\15\46\6\10\4\46\11\10\1\147\15\10\1\46\1\10"+
    "\1\46\3\10\1\46\1\47\1\50\1\46\2\10\15\46"+
    "\6\10\4\46\2\10\1\150\24\10\1\46\1\10\1\46"+
    "\3\10\1\46\1\47\1\50\1\46\2\10\15\46\6\10"+
    "\4\46\1\10\1\151\25\10\1\46\1\10\1\46\3\10"+
    "\1\46\1\47\1\50\1\46\2\10\15\46\6\10\4\46"+
    "\21\10\1\152\5\10\1\46\1\10\1\46\3\10\1\46"+
    "\1\47\1\50\1\46\2\10\15\46\6\10\4\46\12\10"+
    "\1\153\14\10\1\46\1\10\6\55\1\133\1\154\62\55"+
    "\72\0\1\46\3\10\1\46\1\47\1\50\1\46\2\10"+
    "\15\46\6\10\4\46\7\10\1\155\17\10\1\46\1\10"+
    "\1\46\3\10\1\46\1\47\1\50\1\46\2\10\15\46"+
    "\6\10\4\46\1\10\1\156\25\10\1\46\1\10\1\46"+
    "\3\10\1\46\1\47\1\50\1\46\2\10\15\46\5\10"+
    "\1\157\4\46\27\10\1\46\1\10\1\46\3\10\1\46"+
    "\1\47\1\50\1\46\2\10\15\46\6\10\4\46\3\10"+
    "\1\160\23\10\1\46\1\10\1\46\3\10\1\46\1\47"+
    "\1\50\1\46\2\10\15\46\6\10\4\46\1\161\26\10"+
    "\1\46\1\10\1\46\3\10\1\46\1\47\1\50\1\46"+
    "\2\10\15\46\6\10\4\46\6\10\1\162\20\10\1\46"+
    "\1\10\1\46\3\10\1\46\1\47\1\50\1\46\2\10"+
    "\15\46\6\10\4\46\13\10\1\163\13\10\1\46\1\10"+
    "\1\46\3\10\1\46\1\47\1\50\1\46\2\10\15\46"+
    "\6\10\4\46\4\10\1\164\22\10\1\46\1\10\1\46"+
    "\3\10\1\46\1\47\1\50\1\46\2\10\15\46\6\10"+
    "\4\46\1\165\26\10\1\46\1\10\1\46\3\10\1\46"+
    "\1\47\1\50\1\46\2\10\15\46\6\10\4\46\22\10"+
    "\1\166\4\10\1\46\1\10\1\46\3\10\1\46\1\47"+
    "\1\50\1\46\2\10\15\46\6\10\4\46\1\167\26\10"+
    "\1\46\1\10\6\170\1\171\63\170\1\46\3\10\1\46"+
    "\1\47\1\50\1\46\2\10\15\46\6\10\4\46\1\172"+
    "\26\10\1\46\1\10\1\46\3\10\1\46\1\47\1\50"+
    "\1\46\2\10\15\46\6\10\4\46\1\173\26\10\1\46"+
    "\1\10\1\46\3\10\1\46\1\47\1\50\1\46\2\10"+
    "\15\46\1\174\5\10\4\46\27\10\1\46\1\10\1\46"+
    "\3\10\1\46\1\47\1\50\1\46\2\10\15\46\6\10"+
    "\4\46\11\10\1\175\15\10\1\46\1\10\1\46\3\10"+
    "\1\46\1\47\1\50\1\46\2\10\15\46\6\10\4\46"+
    "\25\10\1\176\1\10\1\46\1\10\1\46\3\10\1\46"+
    "\1\47\1\50\1\46\2\10\15\46\1\177\5\10\4\46"+
    "\27\10\1\46\1\10\6\170\1\200\1\0\62\170\1\46"+
    "\3\10\1\46\1\47\1\50\1\46\2\10\15\46\5\10"+
    "\1\201\4\46\27\10\1\46\1\10\1\46\3\10\1\46"+
    "\1\47\1\50\1\46\2\10\15\46\6\10\4\46\6\10"+
    "\1\202\20\10\1\46\1\10\1\46\3\10\1\46\1\47"+
    "\1\50\1\46\2\10\15\46\6\10\4\46\26\10\1\203"+
    "\1\46\1\10\1\46\3\10\1\46\1\47\1\50\1\46"+
    "\2\10\15\46\6\10\4\46\16\10\1\204\10\10\1\46"+
    "\1\10\6\170\1\200\63\170\1\46\3\10\1\46\1\47"+
    "\1\50\1\46\2\10\15\46\5\10\1\205\4\46\27\10"+
    "\1\46\1\10\1\46\3\10\1\46\1\47\1\50\1\46"+
    "\2\10\15\46\6\10\4\46\1\206\26\10\1\46\1\10";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5336];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\44\1\3\0\3\1\1\0\34\1\1\0\22\1"+
    "\1\11\34\1\1\0\15\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[134];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
   
    public static void init(){}
    private Symbol symbol(int type){
        return new Symbol(type,yyline,yycolumn); 
    }
    private Symbol symbol(int type,Object value){
        return new Symbol(type,yyline,yycolumn,value);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 3476) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { System.out.println("Error:"+yytext()+" 是不合法的符号");
            } 
            // fall through
          case 53: break;
          case 2: 
            { try{ 
            if(yylength() > 12)
            throw new RangeException();
            return symbol(sym.NUMBER,new Integer(yytext())); /**//*case {Number}*/
        }catch(RangeException e){}
            } 
            // fall through
          case 54: break;
          case 3: 
            { return symbol(sym.LPAREN); /**//*case "("*/
            } 
            // fall through
          case 55: break;
          case 4: 
            { return symbol(sym.TIMES); /**//*case "*"*/
            } 
            // fall through
          case 56: break;
          case 5: 
            { return symbol(sym.RPAREN); /**//*case ")"*/
            } 
            // fall through
          case 57: break;
          case 6: 
            { try{
            if(yylength() > 24)
                throw new LengthException();
            return symbol(sym.IDENTIFIER,new String(yytext())); /**//*case {Identifer}*/
        }catch(LengthException e){}
            } 
            // fall through
          case 58: break;
          case 7: 
            { /**//*case {WhiteSpace}:  do nothing*/
            } 
            // fall through
          case 59: break;
          case 8: 
            { return symbol(sym.SEMI); /**//*case ";"*/
            } 
            // fall through
          case 60: break;
          case 9: 
            { return symbol(sym.DOT);/**//*case "."*/
            } 
            // fall through
          case 61: break;
          case 10: 
            { return symbol(sym.COMMA);/**//*case ","*/
            } 
            // fall through
          case 62: break;
          case 11: 
            { return symbol(sym.COLON);/**//*case ":"*/
            } 
            // fall through
          case 63: break;
          case 12: 
            { return symbol(sym.RELOP1);/**//*case "<"*/
            } 
            // fall through
          case 64: break;
          case 13: 
            { return symbol(sym.RELOP5);/**//*case "="*/
            } 
            // fall through
          case 65: break;
          case 14: 
            { return symbol(sym.RELOP3);/**//*case ">"*/
            } 
            // fall through
          case 66: break;
          case 15: 
            { return symbol(sym.POUND);/**//*case "#"*/
            } 
            // fall through
          case 67: break;
          case 16: 
            { return symbol(sym.PLUS); /**//*case "+"*/
            } 
            // fall through
          case 68: break;
          case 17: 
            { return symbol(sym.MINUS); /**//*case "-"*/
            } 
            // fall through
          case 69: break;
          case 18: 
            { return symbol(sym.RELOP7);/**//*case "&"*/
            } 
            // fall through
          case 70: break;
          case 19: 
            { return symbol(sym.REVERSE); /**//*case "~"*/
            } 
            // fall through
          case 71: break;
          case 20: 
            { return symbol(sym.LB);/**//*case "["*/
            } 
            // fall through
          case 72: break;
          case 21: 
            { return symbol(sym.RB);/**//*case "]"*/
            } 
            // fall through
          case 73: break;
          case 22: 
            { try{
        throw new NumberException();
        }catch(NumberException e){}
            } 
            // fall through
          case 74: break;
          case 23: 
            { try{
        throw new OctException();
        }catch(OctException e){}
            } 
            // fall through
          case 75: break;
          case 24: 
            { try{
        throw new CommentException();
        }catch(CommentException e){}
            } 
            // fall through
          case 76: break;
          case 25: 
            { return symbol(sym.RELOP8);/**//*case ":="*/
            } 
            // fall through
          case 77: break;
          case 26: 
            { return symbol(sym.RELOP2);/**//*case "<="*/
            } 
            // fall through
          case 78: break;
          case 27: 
            { return symbol(sym.RELOP4);/**//*case ">="*/
            } 
            // fall through
          case 79: break;
          case 28: 
            { return symbol(sym.DO);/**//*case "DO"*/
            } 
            // fall through
          case 80: break;
          case 29: 
            { return symbol(sym.IF);/**//*case "IF"*/
            } 
            // fall through
          case 81: break;
          case 30: 
            { return symbol(sym.OR); /**//*case "OR"*/
            } 
            // fall through
          case 82: break;
          case 31: 
            { return symbol(sym.OF);/**//*case "OF"*/
            } 
            // fall through
          case 83: break;
          case 32: 
            { return symbol(sym.DIVIDE); /**//*case "DIV"*/
            } 
            // fall through
          case 84: break;
          case 33: 
            { return symbol(sym.VAR);/**//*case "VAR"*/
            } 
            // fall through
          case 85: break;
          case 34: 
            { return symbol(sym.MOD); /**//*case "MOD"*/
            } 
            // fall through
          case 86: break;
          case 35: 
            { return symbol(sym.END);/**//*case "END"*/
            } 
            // fall through
          case 87: break;
          case 36: 
            { return symbol(sym.COMMENT,new String(yytext()));
            } 
            // fall through
          case 88: break;
          case 37: 
            { return symbol(sym.READ);/**//*case "Read"*/
            } 
            // fall through
          case 89: break;
          case 38: 
            { return symbol(sym.ELSE);/**//*case "ELSE"*/
            } 
            // fall through
          case 90: break;
          case 39: 
            { return symbol(sym.THEN);/**//*case "THEN"*/
            } 
            // fall through
          case 91: break;
          case 40: 
            { return symbol(sym.TYPE);/**//*case "TYPE"*/
            } 
            // fall through
          case 92: break;
          case 41: 
            { return symbol(sym.ELSIF);/**//*case "ELSIF"*/
            } 
            // fall through
          case 93: break;
          case 42: 
            { return symbol(sym.BEGIN);/**//*case "BEGIN"*/
            } 
            // fall through
          case 94: break;
          case 43: 
            { return symbol(sym.ARRAY);/**//*case "ARRAY"*/
            } 
            // fall through
          case 95: break;
          case 44: 
            { return symbol(sym.CONST);/**//*case "CONST"*/
            } 
            // fall through
          case 96: break;
          case 45: 
            { return symbol(sym.WHILE);/**//*case "WHILE"*/
            } 
            // fall through
          case 97: break;
          case 46: 
            { return symbol(sym.WRITE);/**//*case "Write"*/
            } 
            // fall through
          case 98: break;
          case 47: 
            { return symbol(sym.MODULE);/**//*case "MODULE"*/
            } 
            // fall through
          case 99: break;
          case 48: 
            { return symbol(sym.RECORD);/**//*case "RECORD"*/
            } 
            // fall through
          case 100: break;
          case 49: 
            { return symbol(sym.INTEGER);/**//*case "INTEGER"*/
            } 
            // fall through
          case 101: break;
          case 50: 
            { return symbol(sym.BOOLEAN);/**//*case "BOOLEAN"*/
            } 
            // fall through
          case 102: break;
          case 51: 
            { return symbol(sym.Writeln);/**//*case "Writeln"*/
            } 
            // fall through
          case 103: break;
          case 52: 
            { return symbol(sym.PROCEDURE);/**//*case "PROCEDURE"*/
            } 
            // fall through
          case 104: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
