
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 5;
  public static final int CONST = 25;
  public static final int COMMENT = 38;
  public static final int ELSIF = 31;
  public static final int INTEGER = 17;
  public static final int SEMI = 45;
  public static final int LPAREN = 41;
  public static final int ARRAY = 23;
  public static final int MINUS = 3;
  public static final int WRITE = 19;
  public static final int RPAREN = 42;
  public static final int REVERSE = 15;
  public static final int RECORD = 22;
  public static final int TYPE = 26;
  public static final int OR = 14;
  public static final int COMMA = 47;
  public static final int BEGIN = 35;
  public static final int PLUS = 2;
  public static final int IF = 29;
  public static final int DOT = 48;
  public static final int OF = 37;
  public static final int EOF = 0;
  public static final int BOOLEAN = 18;
  public static final int LB = 43;
  public static final int TRUE = 39;
  public static final int POUND = 16;
  public static final int error = 1;
  public static final int RB = 44;
  public static final int NUMBER = 49;
  public static final int MOD = 6;
  public static final int MODULE = 24;
  public static final int TIMES = 4;
  public static final int COLON = 46;
  public static final int FLASE = 40;
  public static final int ELSE = 32;
  public static final int READ = 20;
  public static final int WHILE = 33;
  public static final int RELOP8 = 7;
  public static final int RELOP7 = 13;
  public static final int THEN = 30;
  public static final int RELOP5 = 12;
  public static final int END = 36;
  public static final int Writeln = 21;
  public static final int RELOP4 = 11;
  public static final int RELOP3 = 10;
  public static final int RELOP2 = 9;
  public static final int RELOP1 = 8;
  public static final int VAR = 27;
  public static final int PROCEDURE = 28;
  public static final int DO = 34;
  public static final int IDENTIFIER = 50;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "MOD",
  "RELOP8",
  "RELOP1",
  "RELOP2",
  "RELOP3",
  "RELOP4",
  "RELOP5",
  "RELOP7",
  "OR",
  "REVERSE",
  "POUND",
  "INTEGER",
  "BOOLEAN",
  "WRITE",
  "READ",
  "Writeln",
  "RECORD",
  "ARRAY",
  "MODULE",
  "CONST",
  "TYPE",
  "VAR",
  "PROCEDURE",
  "IF",
  "THEN",
  "ELSIF",
  "ELSE",
  "WHILE",
  "DO",
  "BEGIN",
  "END",
  "OF",
  "COMMENT",
  "TRUE",
  "FLASE",
  "LPAREN",
  "RPAREN",
  "LB",
  "RB",
  "SEMI",
  "COLON",
  "COMMA",
  "DOT",
  "NUMBER",
  "IDENTIFIER"
  };
}

