
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 22;
  public static final int ELSE = 3;
  public static final int PLUS = 20;
  public static final int RPAREN = 25;
  public static final int SEMI = 18;
  public static final int WHILE = 4;
  public static final int RETURN = 5;
  public static final int IF = 2;
  public static final int LPAREN = 24;
  public static final int ID = 31;
  public static final int LC = 28;
  public static final int LB = 26;
  public static final int RC = 29;
  public static final int RB = 27;
  public static final int RANDOM = 6;
  public static final int RELOP8 = 17;
  public static final int NUMBER = 30;
  public static final int EOF = 0;
  public static final int RELOP7 = 16;
  public static final int DIVIDE = 23;
  public static final int RELOP6 = 15;
  public static final int RELOP5 = 14;
  public static final int MAIN = 8;
  public static final int RELOP4 = 13;
  public static final int RELOP3 = 12;
  public static final int RELOP2 = 11;
  public static final int MINUS = 21;
  public static final int RELOP1 = 10;
  public static final int DOT = 19;
  public static final int PRINT = 9;
  public static final int error = 1;
  public static final int VAR = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "ELSE",
  "WHILE",
  "RETURN",
  "RANDOM",
  "VAR",
  "MAIN",
  "PRINT",
  "RELOP1",
  "RELOP2",
  "RELOP3",
  "RELOP4",
  "RELOP5",
  "RELOP6",
  "RELOP7",
  "RELOP8",
  "SEMI",
  "DOT",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "LPAREN",
  "RPAREN",
  "LB",
  "RB",
  "LC",
  "RC",
  "NUMBER",
  "ID"
  };
}

